name: "Review Actions"

on:
  pull_request:
    types: [review_requested, review_request_removed]
  pull_request_review:
    types: [submitted]

jobs:
  postreview:
    runs-on: ubuntu-latest
    if: ${{ (github.event_name == 'pull_request_review') && (github.event.action == 'submitted') }}
    env: r
    steps:
      - name: "Mark PR as ready for merge"
        if: ${{ (github.event.review.state == 'approved') }}
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: "lifecycle/ready-for-merge"
          remove-labels: "status/wip, status/wait-for-review"

      - name: "Mark PR as do not merge"
        if: ${{ (github.event.review.state) == 'request_changes' }}
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: "status/do-not-merge"
          remove-labels: ""
